version: '3.8'

services:
  # The Persistence Engine (User Data)
  db:
    image: postgres:15-alpine
    container_name: sd-postgres
    restart: always
    environment:
      POSTGRES_USER: sd_admin
      POSTGRES_PASSWORD: sd_password
      POSTGRES_DB: social_distance
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  # The Leaderboard Engine (Real-time Ranking)
  cache:
    image: redis:7-alpine
    container_name: sd-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
    command: redis-server --save 60 1 --loglevel warning